services:
  app:
    build: .
    ports:
      - '4003:4003'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env
  db:
    image: mysql:8.0
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE=libamaq_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
volumes:
  mysql-data:
networks:
  app-network:
    driver: bridge