export const stringConstants = {
  noFileUploaded: 'No file uploaded',
  invalidFileType: 'Invalid file type',
  duplicatedEmailAtRow: 'Duplicated email in excel row ',
  missingFieldsAtRow: 'Missing fields in excel row ',
  invalidRoleAtRow: 'Invalid role at row ',
  incorrectAuth: 'Incorrect e-mail or password.',
  duplicateRecord: 'This record already exists.',
  duplicateUser: 'This user already exists',
  duplicateUserAtRow: 'User already exists in excel row ',
  duplicateRole: 'This role already exists',
  duplicateCardUUID: 'The UUID already exists',
  existDefinitiveSolution: 'Already exists a definitive solution',
  existProvisionalSolution: 'Already exists a provisional solution',
  quantityOfUserExceeded: 'Quantity of site user exceeded',
  codeExpired: 'The code has expired',
  wrongResetCode: 'Wrong reset code',
  emailIsMissing: 'The e-mail is missing',
  duplicateLevelMachineId: 'A record with that level machine id already exists',
  resetPasswordEmailSubject: 'Reset Your Password - OSM',
  welcomeEmailSubject: 'Welcome to Our Platform!',
  characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  none: 'None',

  //Roles
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  FREQUENT_CUSTOMER: 'FREQUENT_CUSTOMER',
  GENERAL_CUSTOMER: 'GENERAL_CUSTOMER',
  
  //Status
  STATUS_ACTIVE: 'ACTIVE',
  STATUS_INACTIVE: 'INACTIVE',

  userNotFound: 'User not found',
  brandNotFound: 'Brand not found',
  categoryNotFound: 'Category not found',
  billingInfoNotFound: 'Billing info not found',
  shippingAddressNotFound: 'Shipping address not found',
  orderNotFound: 'Order not found',
  productNotFound: 'Product not found',
  sparePartNotFound: 'Spare part not found',
  mediaNotFound: 'Media not found',
  landingNotFound: 'Landing not found',
  brandCategoryNotFound: 'Brand category not found',
  notFound: 'Not found',
  //sql errors
  INSERT_DATA_ERROR: 'INSERT_DATA_ERROR',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  UNHANDLED_SQL_ERROR: 'UNHANDLED_SQL_ERROR',
  
  SALT_ROUNDS: 10,
  OS_ANDROID: 'ANDROID',
  OS_IOS: 'IOS',
  OS_WEB: 'WEB',
  FILE_TYPE_IMAGE: 'IMAGE',
  FILE_TYPE_PDF: 'PDF',
  FILE_TYPE_VIDEO: 'VIDEO',
  FILE_TYPE_OTHER: 'OTHER',
  ENTITY_TYPE_PRODUCT: 'PRODUCT',
  ENTITY_TYPE_SPARE_PART: 'SPARE_PART',
  ENTITY_TYPE_LANDING: 'LANDING',

  ORDER_HEADER: (orderId: any) => `📦 *Detalles de tu Orden #${orderId}* 📦\n\nAquí tienes un resumen de tu compra. Te enviaremos los documentos detallados en un momento.`,
};
